version: "3.9"  # optional since v1.27.0
services:
  api-aqua:
    image: millegalb/aqua.api:1.0.0
    build:
      context: .
      dockerfile: Backend/Aqua.Api/Dockerfile
    environment:
        - "ASPNETCORE_ENVIRONMENT=Compose"
    ports:
      - "5046:5046"
    networks:
      - sky
    links:
      - sqlserver
  web-aqua:
    image: millegalb/aqua.web:1.0.0
    build:
      context: .
      dockerfile: Backend/Aqua.Web/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Compose"
    ports:
      - "9000:80"
    volumes:
      - ./UI/apps/aqua/build:/app/wwwroot
    networks:
      - sky
    links:
      - api-aqua
      - sqlserver
  web-identity:
    image: millegalb/identity:1.0.0
    build:
      context: .
      dockerfile: Backend/Web.Identity/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Compose"
    ports:
      - "6060:6060"
    volumes:
      - ./UI/apps/identity/build:/app/wwwroot
    networks:
      - sky
  identity-server:
    image: millegalb/identity.server:1.0.0
    build:
      context: .
      dockerfile: Backend/IdentityServer/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Compose"
    ports:
      - "6065:6065"
    restart: on-failure
    networks:
      - sky
    links:
      - sqlserver
  web-list:
    image: millegalb/aqua.list:1.0.0
    build:
      context: .
      dockerfile: Backend/Aqua.List.Web/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Compose"
    ports:
      - "3033:3033"
    volumes:
      - ./UI/apps/admin/build:/app/wwwroot
    networks:
      - sky
  sqlserver:
      image: mcr.microsoft.com/azure-sql-edge:latest
      ports:
        - "1433:1433"
      volumes:
        - sql-data:/var/opt/mssql
      networks:
        - sky
      environment:
        - "MSSQL_SA_PASSWORD=MyPass@word"
        - "MSSQL_PID=Developer"
        - "ACCEPT_EULA=1"
        - "MSSQL_USER=SA"

volumes:
  sql-data:

networks:
  sky:
